### ISSUE TITLE
Disable turn off while turning off

### ISSUE THREAD

**Issue by PascalBu** [nklerk/neeo_driver-kodi#13]
Hi Niels, not sure you will be reading this...

Some strange behaviour with NEEO using your driver for Kodi when turning off the recipe. When removing the "turn of Kodi" part from the recipe, it works when just switching this recipe on and off (so not killing the Raspberry pi running Kodi). However, when you activate another recipe and turn that off, it will kill the RPI running Kodi on it, even though this second recipe has nothing to do with that RPI! Eg Chromecast...

A workaround is also removing the turn on Kodi part from the recipe activation. This does however lead to the recipe not staying alive on the homescreen.

Background: have switched from using Kodi on a PC to RPI, and when this gets switched off, it cannot be easily switched on again.

Any thoughts on why NEEO is terminating Kodi from another recipe? Seems like NEEO related to me?

**Comment by nklerk** [comment]
It’s the way NEEO works internally. You can change https://github.com/nklerk/neeo_driver-kodi/blob/master/devices/kodi/kodi-commands.js

To let power off do something different/ or nothing at all. Also be sure the TV isn’t telling kodi to turn off using HDMI-CEC

**Comment by PascalBu** [comment]
Works as advertised, thanks for the help! And good luck with YIO, I am keeping my eye on that to replace the dying NEEO...
